name: econo_master
description: "EconoMaster is a comprehensive business calculator designed to streamline and simplify the financial calculations and projections for businesses. With a user-friendly interface and a wide range of functionalities, EconoMaster can handle everything from simple calculations to complex financial forecasts. Whether you're calculating profit margins, forecasting revenue growth, or analyzing investment opportunities, EconoMaster is the tool to help you make informed business decisions. Built with Flutter, EconoMaster is a cross-platform application that runs smoothly on both iOS and Android devices."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.5 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_localizations:
    sdk: flutter
dev_dependencies:
  flutter_launcher_icons: "^0.9.2"
flutter_icons:
  ios: true
  image_path: "assets/image.png"
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/lang/
